CREATE TABLE CRM (
    CustomerID INT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    AddressLine1 VARCHAR(100) NOT NULL,
    AddressLine2 VARCHAR(100),
    City VARCHAR(50) NOT NULL,
    State VARCHAR(50) NOT NULL,
    ZipCode VARCHAR(10) NOT NULL,
    Country VARCHAR(50) NOT NULL,
    DateOfBirth DATE,
    Gender CHAR(1),
    PreferredContactMethod VARCHAR(20),
    PreferredLanguage VARCHAR(20),
    CustomerSince DATE NOT NULL,
    LastPurchaseDate DATE,
    TotalSpent DECIMAL(10, 2),
    LastContactDate DATE,
    Notes TEXT,
    MarketingOptIn BOOLEAN,
    LoyaltyProgramMember BOOLEAN,
    LoyaltyPoints INT,
    ReferredBy VARCHAR(50),
    ReferredByCode VARCHAR(20),
    AccountManager VARCHAR(50),
    PreferredStore VARCHAR(50),
    FavoriteProductCategory VARCHAR(50),
    LastProductPurchased VARCHAR(50),
    LastProductRating INT,
    SurveyParticipation BOOLEAN,
    SubscriptionStatus VARCHAR(20),
    SubscriptionStartDate DATE,
    SubscriptionEndDate DATE,
    BillingAddressLine1 VARCHAR(100),
    BillingAddressLine2 VARCHAR(100),
    BillingCity VARCHAR(50),
    BillingState VARCHAR(50),
    BillingZipCode VARCHAR(10),
    BillingCountry VARCHAR(50),
    ShippingAddressLine1 VARCHAR(100),
    ShippingAddressLine2 VARCHAR(100),
    ShippingCity VARCHAR(50),
    ShippingState VARCHAR(50),
    ShippingZipCode VARCHAR(10),
    ShippingCountry VARCHAR(50),
    PaymentMethod VARCHAR(50) NOT NULL,
    CreditLimit DECIMAL(10, 2),
    AccountStatus VARCHAR(20) NOT NULL
);